# Generated by Django 5.0.4 on 2024-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_pic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='monthYear_manufacture',
            field=models.CharField(verbose_name='05-2024'),
        ),
    ]
