# Generated by Django 5.0.4 on 2024-05-06 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_pic', '0002_alter_epic_monthyear_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='monthYear_manufacture',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
